@ControllerBasedAPI_HostAddress = https://localhost:7188

GET {{ControllerBasedAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{ControllerBasedAPI_HostAddress}}/api/todoitems
Content-Type: application/json

{
  "name": "walk dog",
  "isComplete": true
}

###

GET {{ControllerBasedAPI_HostAddress}}/api/todoitems

###
